#!/usr/bin/env python

# read the yaml config and generate the json version for packer

import json, os, sys, yaml
from glob import glob

CWD = os.path.dirname(os.path.realpath(__file__))

def main():
    os.chdir(CWD)
    for name in glob('*-template.yaml'):
        dest = name.replace('-template.yaml', '.json')
        cfg = yaml.load(open(name, 'rb'))
        json.dump(cfg, open(dest, 'wb'), indent=2)

if __name__ == '__main__':
    main()

